using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    /// <summary>Œ»İ‚ÌŠK‘w</summary>
    public static int CurremtLevel => currentLevel;
    public static PlayerStatusSaveData SaveData => saveData;

    [Tooltip("Œ»İ‚ÌŠK‘w")]
    private static int currentLevel = 0;
    private static float score;
    private static PlayerStatusSaveData saveData = new();

    void Start()
    {

    }

    void Update()
    {
        
    }

    /// <summary>
    /// ŠK‘wˆê‚Âã‚ª‚é
    /// </summary>
    public static void NextCurrentLevel() 
    {
        //Ÿ‚ÌŠK‘w‚ğƒ[ƒh‚·‚éˆ—
        currentLevel++;
    }

    public static void ResetCurrentLevel() 
    {
        currentLevel = 0;
    }

    public static void GameOver() 
    {
        //ƒŠƒUƒ‹ƒg‚ÌƒV[ƒ“‚ğŒÄ‚Ño‚·
    }

    /// <summary>
    /// Player‚ÉŠÖ‚·‚éƒf[ƒ^‚ğ•Û‘¶‚·‚é
    /// </summary>
    /// <param name="save"></param>
    public static void SavePlayerData(PlayerStatusSaveData save) 
    {
        saveData = save;
    }
}